spring:
  application:
    name: AuthServer
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:${spring.cloud.config.uri}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    refresh:
      enabled: true

server:
  port: 9000
  address: 127.0.0.1

logging:
  level:
    root: DEBUG
    com.authorization.AuthServer: DEBUG
    org:
      springframework:
        security:
          oauth2: DEBUG

app:
  data:
    test: App data
