spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
  application:
    name: client
server:
  port: 8081

logging:
  level:
    root: DEBUG
    com.authorization.client: DEBUG
    org:
      springframework:
        security:
          oauth2: DEBUG