spring:
  security:
    oauth2:
      resourceserver:
        customOpaqueToken:
          introspectionUri: http://localhost:9000/oauth2/custom-introspect
          clientId: gateway-client
          clientSecret: secret
  application:
    name: client
server:
  port: 8081

logging:
  level:
    root: DEBUG
    com.authorization.client: DEBUG
    org:
      springframework:
        security:
          oauth2: DEBUG