spring:
  application:
    name: client
server:
  port: 8081

logging:
  level:
    root: DEBUG
    com.authorization.client: DEBUG
    org:
      springframework:
        security:
          oauth2: DEBUG

oauth:
  authorization:
    introspectUrl: http://localhost:9000/oauth2/custom-introspect
    clientId: gateway-client
    clientSecret: secret