spring:
  application:
    name: common-config-server
  cloud:
    config:
      server:
        git:
          # Add config files git repo here
          uri: C:\vas\documents\i2i_internal\config-files

server:
  port: 8888
